name: C++ CI with Qt and GitHub Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        host: ubuntu-20.04
        target: desktop
        arch: gcc_64

    - name: Install build dependencies
      run: sudo apt-get install -y build-essential qt5-qmake

    - name: Build project
      run: |
        qmake
        make

    - name: Run unit tests
      run: |
        cd test/
        qmake -makefile
        make
        ./test_game  # Replace with your actual test executable name

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build


