name: CI/CD

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build Qt Project
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.7.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      - name: Set up environment variables
        run: |
          echo C:\Qt\6.7.1\msvc2019_64\bin >> $GITHUB_ENV
          echo C:\Qt\Tools\QtCreator\bin >> $GITHUB_ENV

      - name: Build project
        run: |
          mkdir build
          cd build
          qmake ../qmakewithsounds.pro  # Ensure the path to the .pro file is correct
          nmake

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/

  deploy:
    name: Deploy to Server
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/

